## Step 3

= Verify Application Blocking

== Overview

Now that you've seen how the daemon is configured, let's see fapolicyd in action. You'll install an application from an internet source and observe how fapolicyd blocks execution of untrusted binaries.

== Step 1: Extract an Untrusted Application

Let's install a new application from an internet source, `cowsay`. There is nothing inherently malicious about this binary, though it provides a good example for our application control workflow.

Extract `cowsay` into the user's home directory:

[source,bash,role="execute",subs=attributes+]
----
tar xsf cowsay_2.0.4_Linux_x86_64.tar.gz
----

== Step 2: Execute Before fapolicyd Is Running

You should have no problems executing the `cowsay` binary while fapolicyd is stopped:

[source,bash,role="execute",subs=attributes+]
----
./cowsay "mooooo"
----

== Step 3: Start fapolicyd

Let's start up fapolicyd and see what happens:

[source,bash,role="execute",subs=attributes+]
----
sudo systemctl start fapolicyd
----

== Step 4: Attempt Execution Again

Now run the `cowsay` command again:

[source,bash,role="execute",subs=attributes+]
----
./cowsay "mooooo"
----

You'll obtain the following error:

[source,bash,role="execute",subs=attributes+]
----
-bash: ./cowsay: Operation not permitted
----

[IMPORTANT]
====
Because the `cowsay` binary isn't in the RPM database or the file-backed trust database configured at `/etc/fapolicyd/fapolicyd.trust`, the execution is blocked.
====


Click "Next" to learn how to add trusted applications to the file-backed trust database.
