## Step 5: Explore Integrity Checking

Adding a binary to the trust database allows execution based on file location, but what happens if a trusted binary is replaced with something malicious? In this module, you'll explore fapolicyd's default behavior when a trusted executable is substituted.


**5.1** The `more` command is installed via the RPM database, so it's trusted to execute on the system:
[source,bash,role="execute",subs=attributes+]
----
sudo rpm -qf /bin/more
----


**5.2** Let's verify that fapolicyd is still running:
[source,bash,role="execute",subs=attributes+]
----
sudo systemctl status fapolicyd
----

**5.3** Now let's substitute the `more` command for the `cowsay` binary in our user's home directory:
[source,bash,role="execute",subs=attributes+]
----
sudo /bin/cp ./cowsay /bin/more
----


**5.4** Run the substituted binary:
[source,bash,role="execute",subs=attributes+]
----
/bin/more "mooooo"
----

[IMPORTANT]
====
By default, fapolicyd doesn't check what the file looks like—only where it is executing from. This means that an attacker could potentially hijack the execution path of a trusted file and execute malicious code on behalf of a user.
====

Click "Next" to configure SHA-256 integrity checking to mitigate this risk.
