The File Access Policy Daemon (fapolicyd) controls the execution of
applications based on a user-defined policy, and is one of the most
effective ways to mitigate the risk of untrusted and possibly malicious
applications on the system.

First, verify the install of fapolicyd on your Red Hat Enterprise Linux
system.

[source,bash,run]
----
sudo systemctl status fapolicyd
----

The service exists but is disabled by default on installation.

[source,text]
----
○ fapolicyd.service - File Access Policy Daemon
     Loaded: loaded (/usr/lib/systemd/system/fapolicyd.service; disabled; preset: disabled)
     Active: inactive (dead)
----

Next, inspect the fapolicyd configuration that has been created.

[source,bash,run]
----
sudo cat /etc/fapolicyd/fapolicyd.conf
----

We can see a couple of things have been configured for us by default:

* The daemon is configured in enforcing mode (`+permissive = 0+`),
meaning all unauthorized processes will be blocked. We can optionally
configure the daemon for permissive mode and to log unauthorized
processes, rather than block them.
* A new user has been created on the system for the daemon
(`+uid = fapolicyd+`)
* The default sources of trust are the RPM database and a file-backed
trust database. This means that any packages installed into the RPM
database will be trusted by default. In addition, a file is configured
at `+/etc/fapolicyd/fapolicyd.trust+` which can be used for third-party
binaries and other applications not present in the RPM database.
* There is currently no integrity checking configured
(`+integrity = none+`)
